Repository catouberos/video-store, pull requests merged in 2023-05, with the labels that each got.

#43 feat: implement login/signup scene with minimal actions
  .idea/vcs.xml
  src/main/java/pls_no_shinobu/videostore/HelloApplication.java
  src/main/java/pls_no_shinobu/videostore/SceneController.java
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
  src/main/resources/pls_no_shinobu/videostore/css/colors.css
  src/main/resources/pls_no_shinobu/videostore/css/components.css
  src/main/resources/pls_no_shinobu/videostore/css/main.css
  src/main/resources/pls_no_shinobu/videostore/hello-view.fxml
  src/main/resources/pls_no_shinobu/videostore/images/mail.png
  src/main/resources/pls_no_shinobu/videostore/images/user.png
  src/main/resources/pls_no_shinobu/videostore/signin.fxml
  src/main/resources/pls_no_shinobu/videostore/signup.fxml
Labels: enhancement

#46 feat: (re) implemented barebone GUI with controllers & utils
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  src/main/java/module-info.java
  src/main/java/pls_no_shinobu/videostore/HelloApplication.java
  src/main/java/pls_no_shinobu/videostore/HelloController.java
  src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/SignInController.java
  src/main/java/pls_no_shinobu/videostore/controller/SignUpController.java
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/utils/PaneUtils.java
  src/main/java/pls_no_shinobu/videostore/controller/utils/SceneUtils.java
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
  src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
  src/main/resources/pls_no_shinobu/videostore/css/colors.css
  src/main/resources/pls_no_shinobu/videostore/css/components.css
  src/main/resources/pls_no_shinobu/videostore/css/components/button.css
  src/main/resources/pls_no_shinobu/videostore/css/components/header.css
  src/main/resources/pls_no_shinobu/videostore/css/components/input.css
  src/main/resources/pls_no_shinobu/videostore/css/components/sidebar.css
  src/main/resources/pls_no_shinobu/videostore/css/main.css
  src/main/resources/pls_no_shinobu/videostore/editProfile.fxml
  src/main/resources/pls_no_shinobu/videostore/hello-view.fxml
  src/main/resources/pls_no_shinobu/videostore/img/logoTrans.png
  src/main/resources/pls_no_shinobu/videostore/img/nameTrans.png
  src/main/resources/pls_no_shinobu/videostore/logo/controlPanel.png
  src/main/resources/pls_no_shinobu/videostore/logo/dashBoard.png
  src/main/resources/pls_no_shinobu/videostore/logo/logo.png
  src/main/resources/pls_no_shinobu/videostore/logo/logoWhite.png
  src/main/resources/pls_no_shinobu/videostore/signin.fxml
  src/main/resources/pls_no_shinobu/videostore/signup.fxml
  src/main/resources/pls_no_shinobu/videostore/updateItem.fxml
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: enhancement

#50 feat: implement `Database` interface, and completing `Utils`
  data/customers.csv
  data/items.csv
  src/main/java/pls_no_shinobu/videostore/core/Database.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/main/java/pls_no_shinobu/videostore/utils/FileIOUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/ObjectUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/UserUtils.java
  src/test/java/pls_no_shinobu/videostore/utils/TestFileIOUtils.java
Labels: enhancement

#51 feat: implement barebone Session class
  src/main/java/pls_no_shinobu/videostore/core/Session.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
Labels: enhancement

#52 fix: null check on User setters
  src/main/java/pls_no_shinobu/videostore/model/User.java
Labels: bug

#54 feat: completing project utils (incl. User and Item)
  src/main/java/pls_no_shinobu/videostore/manager/ItemManager.java
  src/main/java/pls_no_shinobu/videostore/utils/FileIOUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/ObjectUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/UserUtils.java
  src/test/java/pls_no_shinobu/videostore/utils/TestFileIOUtils.java
  src/test/java/pls_no_shinobu/videostore/utils/TestUserUtils.java
Labels: enhancement

#56 feat: changing application name, implemented `Database` and `Session` singleton
  build.gradle
  src/main/java/pls_no_shinobu/videostore/VideoStoreApplication.java
  src/main/java/pls_no_shinobu/videostore/controller/SignInController.java
  src/main/java/pls_no_shinobu/videostore/controller/SignUpController.java
  src/main/java/pls_no_shinobu/videostore/controller/utils/SceneUtils.java
  src/main/java/pls_no_shinobu/videostore/core/CSVDatabase.java
  src/main/java/pls_no_shinobu/videostore/core/Database.java
  src/main/java/pls_no_shinobu/videostore/core/Session.java
  src/main/java/pls_no_shinobu/videostore/errors/IncorrectLoginInfo.java
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/main/resources/pls_no_shinobu/videostore/signin.fxml
  src/main/resources/pls_no_shinobu/videostore/signup.fxml
Labels: enhancement

#57 fix: checkUsername now return the correct value
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
Labels: bug

#58 feat: finish implementing GUI features
  src/main/java/module-info.java
  src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: enhancement

#59 feat: implement GUI rent & return features
  data/items.csv
  data/users.csv
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
  src/test/java/pls_no_shinobu/videostore/utils/TestFileIOUtils.java
Labels: enhancement

#62 docs: update README
  README.md
  doc/README.md
Labels: documentation

#64 feat: implement search and sort functions
  src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: enhancement

#66 feat: add store logo, more fields on signup and username special chars check
  src/main/java/pls_no_shinobu/videostore/controller/SignInController.java
  src/main/java/pls_no_shinobu/videostore/controller/SignUpController.java
  src/main/java/pls_no_shinobu/videostore/core/Session.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
  src/main/resources/pls_no_shinobu/videostore/img/shinobu.png
  src/main/resources/pls_no_shinobu/videostore/signin.fxml
  src/main/resources/pls_no_shinobu/videostore/signup.fxml
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
  src/test/java/pls_no_shinobu/videostore/model/TestUser.java
Labels: enhancement

#68 feat: add store name, fix spacing and add username for user dashboard
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: enhancement

#70 fix: extract methods & "fake success" dialogs
  src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
Labels: bug

#77 feat: role progress and major bug fix
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: bug, enhancement

#78 feat: enlarge windows and many, many bug fixes
  src/main/java/pls_no_shinobu/videostore/VideoStoreApplication.java
  src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/UpdateItemController.java
  src/main/java/pls_no_shinobu/videostore/controller/UpdateUserController.java
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/utils/SceneUtils.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/resources/pls_no_shinobu/videostore/signup.fxml
Labels: bug, enhancement

#82 feat: add welcome scene
  src/main/java/pls_no_shinobu/videostore/VideoStoreApplication.java
  src/main/java/pls_no_shinobu/videostore/controller/WelcomeController.java
  src/main/resources/pls_no_shinobu/videostore/css/components.css
  src/main/resources/pls_no_shinobu/videostore/css/components/button.css
  src/main/resources/pls_no_shinobu/videostore/welcome.fxml
Labels: enhancement

#85 fix: re-initiate userdashboard and fix table vgrow
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: bug

#84 docs: added UML diagram to project
  doc/UML.pdf
Labels: documentation

#89 feat: validate password, helper text on signup
  src/main/java/pls_no_shinobu/videostore/controller/SignUpController.java
  src/main/resources/pls_no_shinobu/videostore/signup.fxml
Labels: enhancement

#90 feat: add new filters for dashboards
  src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
  src/main/java/pls_no_shinobu/videostore/controller/utils/PaneUtils.java
  src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
  src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
Labels: enhancement

#91 docs: update contributions info
  doc/README.md
Labels: documentation

#92 docs: update contribution details
  doc/README.md
Labels: documentation

#96 docs: add slides for the project's presentation
  doc/presentation.pdf
Labels: documentation

#94 docs: changes in contribution
  doc/README.md
Labels: documentation

#97 more changes in contribution
  doc/README.md
Labels: documentation

#99 docs: changed user dashboard image
  doc/img/userdashboard.png
Labels: documentation
