Repository catouberos/video-store, pull requests merged in 2023-04, with the labels that each got.

#4 docs: create `README.md`
  README.md
Labels: documentation

#9 feat: implement `CoreUtils` with `ItemUtils` csv parser
  data/customers.txt
  data/items.txt
  src/main/java/pls_no_shinobu/videostore/model/Entity.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/java/pls_no_shinobu/videostore/utils/CoreUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
  src/test/java/pls_no_shinobu/videostore/model/TestItem.java
  src/test/java/pls_no_shinobu/videostore/utils/TestItemUtils.java
Labels: enhancement

#12 feat: implement `User` class
  src/main/java/pls_no_shinobu/videostore/model/User.java
Labels: enhancement

#17 fix: implemented check for `User`'s setter methods
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/test/java/pls_no_shinobu/videostore/model/TestUser.java
Labels: enhancement

#21 feat: implement password hasher & hash the password for `User` class
  src/main/java/pls_no_shinobu/videostore/drivers/PasswordHasher.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/test/java/pls_no_shinobu/videostore/drivers/TestPasswordHasher.java
Labels: enhancement

#27 feat: implement `User` renting methods and `Transaction` class
  src/main/java/pls_no_shinobu/videostore/errors/NotFoundException.java
  src/main/java/pls_no_shinobu/videostore/errors/OutOfStockException.java
  src/main/java/pls_no_shinobu/videostore/errors/RentLimitException.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/java/pls_no_shinobu/videostore/model/Transaction.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/test/java/pls_no_shinobu/videostore/model/TestItem.java
  src/test/java/pls_no_shinobu/videostore/model/TestUser.java
Labels: enhancement

#31 feat: implemented `Manager` abstract class with `UserManager` and test cases
  src/main/java/pls_no_shinobu/videostore/errors/DuplicateException.java
  src/main/java/pls_no_shinobu/videostore/manager/Manager.java
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
  src/test/java/pls_no_shinobu/videostore/manager/UserManagerTest.java
Labels: enhancement

#33 fix: redone constructors and removed unused code
  src/main/java/pls_no_shinobu/videostore/manager/Manager.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/test/java/pls_no_shinobu/videostore/model/TestItem.java
  src/test/java/pls_no_shinobu/videostore/model/TestUser.java
Labels: bug

#34 feat: introduce more feature to `Transaction` and a constructor for `UserManager`
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
  src/main/java/pls_no_shinobu/videostore/model/Transaction.java
  src/test/java/pls_no_shinobu/videostore/manager/TestUserManager.java
Labels: enhancement

#35 feat: `Manager` implementations, a lot of refactoring and doc updates
  src/main/java/pls_no_shinobu/videostore/errors/ManagerLimitException.java
  src/main/java/pls_no_shinobu/videostore/manager/AbstractManager.java
  src/main/java/pls_no_shinobu/videostore/manager/Manager.java
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
  src/main/java/pls_no_shinobu/videostore/model/Entity.java
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/main/java/pls_no_shinobu/videostore/utils/CSVUtils.java
  src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
  src/test/java/pls_no_shinobu/videostore/manager/TestUserManager.java
  src/test/java/pls_no_shinobu/videostore/model/TestItem.java
Labels: documentation, enhancement

#39 feat: add find method for `TransactionManager`
  src/main/java/pls_no_shinobu/videostore/manager/TransactionManager.java
Labels: enhancement

#40 feat: change how `User` store rentals (replace `Transaction` with `Item`)
  src/main/java/pls_no_shinobu/videostore/model/User.java
  src/test/java/pls_no_shinobu/videostore/model/TestUser.java
Labels: enhancement

#41 docs: update JavaDoc `Entity` link
  src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
Labels: documentation

#42 feat: implement serialize and add docs for `ItemUtils`, with updated test
  src/main/java/pls_no_shinobu/videostore/model/Item.java
  src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
  src/test/java/pls_no_shinobu/videostore/utils/TestItemUtils.java
Labels: documentation, enhancement
